### ISSUE TITLE
win-system] mingw] this use of defined may not be portable [-Wexpansion-to-defined]

### ISSUE THREAD

**Issue by sallecta** [sallecta/kvnc#99]
MinGW\i686-w64-mingw32\include\psdk_inc\intrin-impl.h|1327|warning: this use of "defined" may not be portable [-Wexpansion-to-defined]

**Comment by sallecta** [comment]
lot of warnings of this type

**Comment by shizhijie1** [comment]
Hello, I also met this problem, how did you solve it, can you tell me briefly, thank you!
